# Generated by Django 4.2 on 2023-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_featured',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
    ]
